# -*- coding: utf-8 -*-
"""Banco_do_Stark_3.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiru_BtMKEMt6uYVqjtPVCq4eSgXUG1R
"""

import importlib
import subprocess
import sys

try:
    requests = importlib.import_module("requests")
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "requests", "-q"])
    requests = importlib.import_module("requests")

import json
from IPython.display import Image, display

print("Bibliotecas carregadas com sucesso!")

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []

print("Classe Conta criada com sucesso!")

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if not isinstance(titular, str) or not titular.strip():
            print("ERRO - Titular inválido.")
            return False
        titular = titular.strip()
        if titular in self.contas:
            print("ERRO - Conta já existe para:", titular)
            return False
        self.contas[titular] = Conta(titular)
        print("OK - Conta criada para:", titular)
        return True

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print("ERRO - Conta não encontrada:", titular)
            return False
        if not isinstance(valor, (int, float)):
            print("ERRO - O valor do depósito precisa ser numérico.")
            return False
        if valor <= 0:
            print("ERRO - O valor do depósito deve ser maior que zero.")
            return False
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(("deposito", valor))
        print("OK - Depósito realizado:", valor)
        return True

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print("ERRO - Conta não encontrada:", titular)
            return False
        if not isinstance(valor, (int, float)):
            print("ERRO - O valor do saque precisa ser numérico.")
            return False
        if valor <= 0:
            print("ERRO - O valor do saque deve ser maior que zero.")
            return False
        if self.contas[titular].saldo < valor:
            print("ERRO - Saldo insuficiente.")
            return False
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(("saque", valor))
        print("OK - Saque realizado:", valor)
        return True

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print("ERRO - Conta origem não encontrada.")
            return False
        if destino not in self.contas:
            print("ERRO - Conta destino não encontrada.")
            return False
        if origem == destino:
            print("ERRO - Não é permitido transferir para a mesma conta.")
            return False
        if not isinstance(valor, (int, float)):
            print("ERRO - O valor da transferência precisa ser numérico.")
            return False
        if valor <= 0:
            print("ERRO - O valor da transferência deve ser maior que zero.")
            return False
        if self.contas[origem].saldo < valor:
            print("ERRO - Saldo insuficiente.")
            return False
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(("transferencia_saida", valor, destino))
        self.contas[destino].extrato.append(("transferencia_entrada", valor, origem))
        print("OK - Transferência realizada:", valor)
        return True

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print("ERRO - Conta não encontrada:", titular)
            return None
        saldo = self.contas[titular].saldo
        print(f"SALDO de {titular} = R$ {saldo:.2f}")
        return saldo

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print("ERRO - Conta não encontrada:", titular)
            return None
        print("EXTRATO de", titular)
        if not self.contas[titular].extrato:
            print(" - Nenhuma movimentação registrada.")
            return []
        for item in self.contas[titular].extrato:
            print(" -", item)
        return self.contas[titular].extrato

print("Classe BancoDoStark criada com validações!")

banco = BancoDoStark()
print("Sistema do Banco do Stark iniciado!")

print("=== CRIAÇÃO DE CONTAS ===")
banco.criar_conta("Tony Stark")
banco.criar_conta("Pepper Potts")
banco.criar_conta("Bruce Banner")

print("\n=== DEPÓSITOS ===")
banco.depositar("Tony Stark", 1000)
banco.depositar("Pepper Potts", 500)

print("\n=== SAQUE ===")
banco.sacar("Tony Stark", 200)

print("\n=== TRANSFERÊNCIA ===")
banco.transferir("Tony Stark", "Pepper Potts", 150)

print("\n=== SALDOS ===")
banco.saldo_atual("Tony Stark")
banco.saldo_atual("Pepper Potts")
banco.saldo_atual("Bruce Banner")

print("\n=== EXTRATO ===")
banco.mostrar_extrato("Tony Stark")

print("=== TESTES NEGATIVOS ===")

print("\nTeste 1 - Criar conta com nome vazio")
banco.criar_conta("")

print("\nTeste 2 - Depósito com valor zero")
banco.depositar("Tony Stark", 0)

print("\nTeste 3 - Depósito com valor negativo")
banco.depositar("Tony Stark", -100)

print("\nTeste 4 - Saque com valor negativo")
banco.sacar("Tony Stark", -50)

print("\nTeste 5 - Saque acima do saldo")
banco.sacar("Tony Stark", 999999)

print("\nTeste 6 - Transferência para a mesma conta")
banco.transferir("Tony Stark", "Tony Stark", 100)

print("\nTeste 7 - Transferência com destino inexistente")
banco.transferir("Tony Stark", "Thor", 100)

BASE_API = "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api"

def consultar_heroi_por_id(hero_id: int, session=requests):
    url = f"{BASE_API}/id/{hero_id}.json"
    print("Consultando URL:", url)
    try:
        resposta = session.get(url, timeout=20)
        print("Status code:", resposta.status_code)
        if resposta.status_code != 200:
            print("ERRO - Não foi possível encontrar o herói na API.")
            return None
        return resposta.json()
    except Exception as erro:
        print("ERRO de comunicação com a API:", erro)
        return None

heroi = consultar_heroi_por_id(224)

print("\nRetorno bruto da API:")
if heroi:
    print(json.dumps(heroi, indent=2, ensure_ascii=False)[:2000])
else:
    print("Nenhum dado retornado.")

if heroi:
    print("Nome:", heroi["name"])
    print("Nome completo:", heroi["biography"]["fullName"])
    print("Editora:", heroi["biography"]["publisher"])
    print("Alinhamento:", heroi["biography"]["alignment"])
    print("Primeira aparição:", heroi["biography"]["firstAppearance"])
    print("Imagem (média):", heroi["images"]["md"])
else:
    print("Nenhum dado para exibir.")

if heroi:
    display(Image(url=heroi["images"]["md"], width=250))
else:
    print("Imagem não disponível porque o herói não foi carregado.")

heroi_invalido = consultar_heroi_por_id(100)
print("Resultado final:", heroi_invalido)

class BancoDoStarkMarvel(BancoDoStark):
    def validar_heroi_marvel(self, hero_id: int, session=requests):
        dados = consultar_heroi_por_id(hero_id, session=session)
        if not dados:
            print("ERRO - Herói não encontrado na API.")
            return None
        publisher = dados.get("biography", {}).get("publisher")
        if publisher != "Marvel Comics":
            print("ERRO - O herói encontrado não pertence à Marvel Comics.")
            return None
        print(f"OK - Herói validado: {dados['name']} ({publisher})")
        return dados

    def criar_conta_com_heroi(self, titular: str, hero_id: int, session=requests):
        heroi = self.validar_heroi_marvel(hero_id, session=session)
        if not heroi:
            print("Conta não criada por falha na validação externa.")
            return False
        conta_criada = self.criar_conta(titular)
        if conta_criada:
            self.contas[titular].extrato.append(("validacao_api", hero_id, heroi["name"]))
            print(f"OK - Conta vinculada ao herói {heroi['name']}!")
            return True
        return False

banco_marvel = BancoDoStarkMarvel()
print("Banco do Stark Marvel iniciado!")

banco_marvel.criar_conta_com_heroi("Annihilus", 29)

banco_marvel.criar_conta_com_heroi("Petter Parker", 620)

banco_marvel.saldo_atual("Petter Parker")
banco_marvel.mostrar_extrato("Petter Parker")

banco_marvel.criar_conta_com_heroi("Loki", 9999)

banco_marvel.saldo_atual("Loki")

def testar_status_e_campos_do_heroi(hero_id: int, session=requests):
    dados = consultar_heroi_por_id(hero_id, session=session)
    assert dados is not None, "A API não retornou dados para um herói válido."
    assert "name" in dados, "Campo 'name' não encontrado."
    assert "biography" in dados, "Campo 'biography' não encontrado."
    assert "powerstats" in dados, "Campo 'powerstats' não encontrado."
    assert dados["biography"]["publisher"] == "Marvel Comics", "Editora inesperada."
    print("Teste 1: PASSOU")

def testar_heroi_inexistente(hero_id: int, session=requests):
    dados = consultar_heroi_por_id(hero_id, session=session)
    assert dados is None, "Era esperado None para um herói inexistente."
    print("Teste 2: PASSOU")

testar_status_e_campos_do_heroi(10)

testar_heroi_inexistente(9999)