# -*- coding: utf-8 -*-
"""QA_Banco_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129Y7tMHSZ98oK63dOCA95pC0VjaVUPWi

Criando a CLASSE conta
"""

class Conta:
    def __init__(self, titular):
        self.titular = titular
        self.saldo = 0
        self.extrato = []

print('Classe Conta criada')

"""Criando o Banco"""

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular):
        if titular in self.contas:
            print('Conta já existe')
            return

        self.contas[titular] = Conta(titular)
        print('Conta criada para', titular)

print('Classe Banco criada')

"""Criando as operações Bancárias"""

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular):
        if titular in self.contas:
            print('Conta já existe')
            return
        self.contas[titular] = Conta(titular)
        print('Conta criada para', titular)

    def depositar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito',valor))

        print('Depósito realizado:',valor)

    def sacar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        if self.contas[titular].saldo < valor:
            print('Saldo insuficiente')
            return

        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque',valor))

        print('Saque realizado:',valor)

    def saldo(self, titular):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        print('Saldo de', titular, '=', self.contas[titular].saldo)

print('Operações adicionadas')

banco = BancoDoStark()
print('Banco Stark em Funcionamento')

"""Caminho Feliz"""

banco.criar_conta('Tony')
banco.criar_conta('Steve')
banco.criar_conta('Bruce')
banco.criar_conta('Thor')

banco.depositar('Tony', 5000)
banco.depositar('Steve', 10000)
banco.depositar('Bruce', 15000)
banco.depositar('Thor', 20000)

banco.sacar('Tony', 1000)
banco.sacar('Steve', 1000)
banco.sacar('Bruce', 1000)
banco.sacar('Thor', 1000)

banco.saldo('Tony')
banco.saldo('Steve')
banco.saldo('Bruce')
banco.saldo('Thor')

"""QA - Testes Negativos"""

banco.criar_conta('123')

banco.depositar('123', -1000)
banco.depositar('Tony', -50000)

banco.depositar('Bruce', 999999999999999999999999999999999999999999999999999999999999999999999999999)

banco.depositar('Thor', 0)

"""Transferências????"""

def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

transferir(banco, 'Tony','Thor', 4500)

banco.saldo('Tony')

banco.depositar('Tony', 450000)