# -*- coding: utf-8 -*-
"""Giovanna_QA_SWAPI_atividade_grupo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBWq7Hiv18Zey3b1Ae2vT2HGzjQAAhUU

# Atividade Prática — QA com APIs (SWAPI)

## Versão do aluno — com scripts base

**Tempo estimado:** 60 minutos  
**Ferramenta:** Google Colab  
**Formato:** em grupos de **2 a 4 componentes** ou, se preferirem, **individualmente**.  
**Objetivo:** investigar respostas de uma API, ajustar scripts simples e responder às perguntas como um QA.

### Instruções
Nesta atividade, vocês **não precisam criar tudo do zero**.  
Os scripts já estão prontos como base. A tarefa do grupo será:

1. **Executar** os blocos de código
2. **Alterar apenas o que for pedido**
3. **Observar os resultados**
4. **Responder às perguntas em Markdown**
5. **Discutir em grupo** quais validações um QA faria

### Entrega
Cada grupo pode entregar **um único notebook** com:
- nomes dos integrantes
- respostas das perguntas
- scripts ajustados
- asserts completados

Se alguém optar por fazer sozinho, pode entregar individualmente sem problema.
"""

import requests
import json

# -------------------------
# MODO DE SEGURANÇA (fallback)
# -------------------------
# Se a API não responder, o notebook usa dados locais
# para a atividade continuar funcionando.

DADOS_FALLBACK = {
    "https://swapi.dev/api/people/10/": {
        "name": "Obi-Wan Kenobi",
        "height": "182",
        "mass": "77",
        "eye_color": "blue-gray",
        "gender": "male",
        "url": "https://swapi.dev/api/people/10/"
    },
    "https://swapi.dev/api/people/13/": {
        "name": "Chewbacca",
        "height": "228",
        "mass": "112",
        "eye_color": "blue",
        "gender": "male",
        "url": "https://swapi.dev/api/people/13/"
    },
    "https://swapi.dev/api/planets/2/": {
        "name": "Alderaan",
        "climate": "temperate",
        "terrain": "grasslands, mountains",
        "population": "2000000000",
        "url": "https://swapi.dev/api/planets/2/"
    },
    "https://swapi.dev/api/starships/10/": {
        "name": "Millennium Falcon",
        "model": "YT-1300 light freighter",
        "manufacturer": "Corellian Engineering Corporation",
        "max_atmosphering_speed": "1050",
        "url": "https://swapi.dev/api/starships/10/"
    }
}

class RespostaLocal:
    def __init__(self, status_code, data):
        self.status_code = status_code
        self._data = data
        self.text = json.dumps(data, ensure_ascii=False)

    def json(self):
        return self._data

def buscar_endpoint(url):
    try:
        resposta = requests.get(url, timeout=10)
        if resposta.status_code == 200:
            return resposta, "online"
    except Exception:
        pass

    if url in DADOS_FALLBACK:
        return RespostaLocal(200, DADOS_FALLBACK[url]), "fallback local"

    return RespostaLocal(404, {"detail": "Not found"}), "fallback local"

print("Ambiente preparado com sucesso.")

"""## Identificação do grupo

- Integrante 1: Arthur Mattos Santana
- Integrante 2: Enzo Fauto Lenon de Oliveira Zimbrão
- Integrante 3 (se houver): Giovanna Bottcher Dias
- Integrante 4 (se houver):

## Parte 1 — Explorando a API

Nesta primeira parte, vocês vão consultar 4 endpoints.  
O trabalho do grupo será **alterar apenas a URL** em cada bloco, executar e observar o retorno.

### 1.1 Personagem 10

**Tarefa:** execute o script e observe:
- status code
- nome
- altura
- cor dos olhos
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Personagem 10**

- Status code: 200
- Nome do personagem: Obi-Wan Kenobi
- Altura: 182
- Cor dos olhos: blue-gray
- O JSON parece completo? Sim

### 1.2 Personagem 13

**Tarefa:** neste bloco, troque apenas o endpoint se necessário, execute e observe o retorno.
"""

url = "https://swapi.dev/api/people/13/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Personagem 13**

- Status code: 200
- Nome do personagem: Chewbacca
- Altura: 228
- Cor dos olhos: blue
- O JSON parece completo? Sim

### 1.3 Planeta 2

**Tarefa:** execute o bloco e observe:
- nome do planeta
- clima
- terreno
- população
"""

url = "https://swapi.dev/api/planets/2/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Planeta 2**

- Status code: 200
- Nome do planeta: Alderaan
- Clima: temperate
- Terreno: grasslands, mountains
- População: 2000000000
- O JSON parece completo? Sim

### 1.4 Nave 10

**Tarefa:** execute o bloco e observe:
- nome da nave
- modelo
- fabricante
- velocidade máxima em atmosfera
"""

url = "https://swapi.dev/api/starships/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Nave 10**

- Status code: 200
- Nome da nave: Millennium Falcon
- Modelo: YT-1300 light freighter
- Fabricante: Corellian Engineering Corporation
- Velocidade máxima em atmosfera: 1050
- O JSON parece completo? Sim

## Parte 2 — Extraindo campos específicos

Agora você vai executar os scripts e **completar as respostas**.

### 2.1 Extraindo campos do personagem

**Tarefa:** execute o bloco e depois responda.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome:", dados["name"])
print("Altura:", dados["height"])
print("Cor dos olhos:", dados["eye_color"])
print("Gênero:", dados["gender"])

"""**Perguntas**
1. Qual campo foi usado para mostrar o nome? Name
2. Qual campo foi usado para mostrar a altura? Height
3. Se você fosse QA, quais desses campos validaria primeiro? Nome

### 2.2 Extraindo campos do planeta

**Tarefa:** execute o bloco e complete as respostas.
"""

url = "https://swapi.dev/api/planets/2/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome do planeta:", dados["name"])
print("Clima:", dados["climate"])
print("Terreno:", dados["terrain"])
print("População:", dados["population"])

"""**Perguntas**
1. O campo população parece numérico? Sim
2. O clima foi retornado corretamente? Sim
3. Se você fosse QA, o que validaria nesse planeta? Nome

## Parte 3 — Pensando como QA

Agora você vai trabalhar com validações simples.

### 3.1 Validações básicas

**Tarefa:** execute o bloco abaixo e depois escreva o que cada validação verifica.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Validação 1 - status 200:", response.status_code == 200)
print("Validação 2 - campo 'name' existe:", "name" in dados)
print("Validação 3 - nome não está vazio:", dados["name"] != "")
print("Validação 4 - campo 'height' existe:", "height" in dados)

"""**Explique com suas palavras**
1. O que a validação 1 verifica? Verifica se o objeto foi criado.
2. O que a validação 2 verifica? Se o nome existe.
3. O que a validação 3 verifica? Verifica se o campo não está vazio.
4. O que a validação 4 verifica? Verifica se o campo da altura existe.

### 3.2 Complete as validações

**Tarefa:** execute o bloco abaixo. Ele já está funcionando. Depois, alterem as expressões se o professor pedir outra nave ou outro endpoint. Em seguida, expliquem por que cada validação faz sentido para QA.
"""

url = "https://swapi.dev/api/starships/2/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Status 200:", response.status_code == 200)

# Os exemplos abaixo já estão corretos e executáveis.
# Se o professor pedir, vocês podem alterar para validar outros campos.
print("Campo 'name' existe:", "name" in dados)
print("Campo 'model' existe:", "model" in dados)
print("Nome não está vazio:", dados["name"] != "")

"""## Parte 4 — Testes automatizados com assert

Agora vocês vão trabalhar sobre scripts já prontos. Os asserts abaixo já executam sem erro. A tarefa do grupo é **entender o que cada linha valida**, ajustar se o professor pedir outro recurso e registrar as respostas.

### 4.1 Assert no personagem

**Tarefa:** execute o bloco. Depois, expliquem o que cada assert valida e, se quiserem, alterem o endpoint para outro personagem.
"""

url = "https://swapi.dev/api/people/13/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "name" in dados, "Erro: campo name não encontrado"
assert dados["name"] != "", "Erro: nome vazio"

print("Todos os testes do personagem passaram!")

"""1 - assert response.status_code == 200, "Erro: status inesperado"

#Valida se a requisição HTTP foi bem-sucedida.
#O código 200 significa que o servidor respondeu corretamente e o endpoint existe.
#Se o código fosse 404, 500 ou outro, o teste falharia indicando problema no endpoint.


2 - assert "name" in dados, "Erro: campo name não encontrado"

#Valida se o campo name está presente no JSON retornado pela API.
#Isso garante que a estrutura da resposta contém a informação esperada do personagem.


3- assert dados["name"] != "", "Erro: nome vazio"

#Valida se o campo name não está vazio.
#Mesmo que o campo exista, ele não pode retornar uma string vazia, garantindo que há realmente um valor válido para o nome do personagem.

### 4.2 Assert na nave

**Tarefa:** execute o bloco. Depois, descrevam qual campo foi validado em cada assert e proponham mais 1 validação extra em Markdown.
"""

url = "https://swapi.dev/api/starships/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "manufacturer" in dados, "Erro: fabricante não encontrado"
assert dados["model"] != "", "Erro: modelo vazio"

print("Todos os testes da nave passaram!")

"""1 - assert response.status_code == 200, "Erro: status inesperado"
#Verifica se a requisição foi bem-sucedida e se o servidor respondeu corretamente.

2 - assert "manufacturer" in dados, "Erro: fabricante não encontrado"
#Valida se o campo manufacturer está presente na resposta da API.
#Esse campo indica qual empresa fabricou a nave.

3 - assert dados["model"] != "", "Erro: modelo vazio"
#Verifica se o campo model não está vazio.
#Isso garante que a nave possui um modelo definido no retorno da API.


#Validação extra (Proposta)

assert "crew" in dados, "Erro: campo crew não encontrado"
assert dados["crew"] != "", "Erro: valor de tripulação vazio"
#Essa validação garante que a API retorna corretamente a quantidade de tripulantes da nave.

## Parte 5 — Cenário negativo

Agora você vai observar como a API se comporta quando pedimos um recurso inexistente.
"""

url = "https://swapi.dev/api/people/9999/"
response, origem = buscar_endpoint(url)

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print("Texto retornado:")
print(response.text)

"""**Perguntas**
1. Qual status code foi retornado? 404
2. Esse comportamento está correto? Sim
3. Por que um QA deve testar cenários negativos? Para evitar o máximo de falhas para o usuário final.

## Parte 6 — Mini desafio final

Agora você vai alterar apenas o endpoint da função abaixo e gerar um pequeno resumo.
"""

def resumo_recurso(url):
    response, origem = buscar_endpoint(url)
    print("Origem dos dados:", origem)
    print("Status Code:", response.status_code)

    if response.status_code != 200:
        print("Recurso não encontrado.")
        return

    dados = response.json()

    for chave, valor in dados.items():
        print(f"{chave}: {valor}")

# ALTERE O ENDPOINT ABAIXO PARA TESTAR OUTRO RECURSO
resumo_recurso("https://swapi.dev/api/planets/2/")

"""**Respostas finais**
1. Qual endpoint você testou no desafio? https://swapi.dev/api/planets/2/

2.  Qual foi o status code?
200

3.  Qual campo chamou mais a sua atenção?
O campo population, pois mostra a quantidade de habitantes do planeta.

4.  Se você fosse QA, quais 3 validações faria nesse recurso?
  1 - verificar se o status code é 200
  2 - verificar se o campo name existe
  3 - verificar se o campo population não está vazio

# Entrega da atividade

Entreguem:

1. O notebook preenchido  
2. As respostas em Markdown  
3. Os scripts ajustados  
4. Os asserts analisados e/ou adaptados  
5. Uma conclusão curta do grupo: **quais foram as 3 validações mais importantes?**

## Fechamento
Ao final desta atividade, vocês praticaram:

- leitura de resposta JSON
- análise de status code
- validação de campos
- pensamento de QA
- testes simples com assert
- análise de cenário negativo
"""