# -*- coding: utf-8 -*-
# Luis_Henrique_do_Carmo_Santos_QA_SWAPI_atividade_grupo.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1UJINovkaAw7cQKnjFWJyCh5Dtkht92aJ

# Atividade Prática — QA com APIs (SWAPI)

# ## Versão do aluno — com scripts base asas

# **Tempo estimado:** 60 minutos  

# **Ferramenta:** Google Colab  

# **Formato:** em grupos de **2 a 4 componentes** ou, se preferirem, **individualmente**.  

# **Objetivo:** investigar respostas de uma API, ajustar scripts simples e responder às perguntas como um QA.

# ### Instruções

# Nesta atividade, vocês **não precisam criar tudo do zero**.  

# Os scripts já estão prontos como base. A tarefa do grupo será:

# 1. **Executar** os blocos de código

# 2. **Alterar apenas o que for pedido**

# 3. **Observar os resultados**

# 4. **Responder às perguntas em Markdown**

# 5. **Discutir em grupo** quais validações um QA faria

# ### Entrega

# Cada grupo pode entregar **um único notebook** com:

# - nomes dos integrantes

# - respostas das perguntas

# - scripts ajustados

# - asserts completados

# Se alguém optar por fazer sozinho, pode entregar individualmente sem problema.

# """

import requests
import json

# -------------------------
# MODO DE SEGURANÇA (fallback)
# -------------------------
# Se a API não responder, o notebook usa dados locais
# para a atividade continuar funcionando.

DADOS_FALLBACK = {
    "https://swapi.dev/api/people/10/": {
        "name": "Obi-Wan Kenobi",
        "height": "182",
        "mass": "77",
        "eye_color": "blue-gray",
        "gender": "male",
        "url": "https://swapi.dev/api/people/10/"
    },
    "https://swapi.dev/api/people/13/": {
        "name": "Chewbacca",
        "height": "228",
        "mass": "112",
        "eye_color": "blue",
        "gender": "male",
        "url": "https://swapi.dev/api/people/13/"
    },
    "https://swapi.dev/api/planets/2/": {
        "name": "Alderaan",
        "climate": "temperate",
        "terrain": "grasslands, mountains",
        "population": "2000000000",
        "url": "https://swapi.dev/api/planets/2/"
    },
    "https://swapi.dev/api/starships/10/": {
        "name": "Millennium Falcon",
        "model": "YT-1300 light freighter",
        "manufacturer": "Corellian Engineering Corporation",
        "max_atmosphering_speed": "1050",
        "url": "https://swapi.dev/api/starships/10/"
    }
}

class RespostaLocal:
    def __init__(self, status_code, data):
        self.status_code = status_code
        self._data = data
        self.text = json.dumps(data, ensure_ascii=False)

    def json(self):
        return self._data

def buscar_endpoint(url):
    try:
        resposta = requests.get(url, timeout=10)
        if resposta.status_code == 200:
            return resposta, "online"
    except Exception:
        pass

    if url in DADOS_FALLBACK:
        return RespostaLocal(200, DADOS_FALLBACK[url]), "fallback local"

    return RespostaLocal(404, {"detail": "Not found"}), "fallback local"

print("Ambiente preparado com sucesso.")

# """## Identificação do grupo
# - Integrante 1: André Queiroz Cenque 86717
# - Integrante 2: Kayque Estevão de Queiroga 89632
# - Integrante 3  Luis Henrique do Carmo Santos 7722
# - Integrante 4  Marina Duarte Cabral RA: 94306
# ## Parte 1 — Explorando a API
# Nesta primeira parte, vocês vão consultar 4 endpoints.  
# O trabalho do grupo será **alterar apenas a URL** em cada bloco, executar e observar o retorno.
# ### 1.1 Personagem 10
# **Tarefa:** execute o script e observe:
# - status code
# - nome
# - altura
# - cor dos olhos
# """

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Personagem 10**

- Status code: 200
- Nome do personagem: Obi-Wan Kenobi
- Altura: 182
- Cor dos olhos: blue-gray
- O JSON parece completo? Sim, aparece completo contendo todas as informações da pessoa.

### 1.2 Personagem 13

**Tarefa:** neste bloco, troque apenas o endpoint se necessário, execute e observe o retorno.
"""

url = "https://swapi.dev/api/people/50/" #
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Personagem 13**

- Status code: 200
- Nome do personagem: Ben Quadinaros
- Altura: 163
- Cor dos olhos: orange
- O JSON parece completo? Não, no campo de ano de nascimento não retornou o dado, deu unknown.

### 1.3 Planeta 2

**Tarefa:** execute o bloco e observe:
- nome do planeta
- clima
- terreno
- população
"""

url = "https://swapi.dev/api/planets/2/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Planeta 2**

- Status code: 200
- Nome do planeta: Alderaan
- Clima: temperate
- Terreno:  pradarias, montanhas
- População: 2000000000
- O JSON parece completo? Sim, apareceu completo contendo todas as informações.

### 1.4 Nave 10

**Tarefa:** execute o bloco e observe:
- nome da nave
- modelo
- fabricante
- velocidade máxima em atmosfera
"""

url = "https://swapi.dev/api/starships/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Nave 10**

- Status code: 200
- Nome da nave: Millennium Falcon
- Modelo: YT-1300 light freighter
- Fabricante: Corellian Engineering Corporation
- Velocidade máxima em atmosfera: 1050
- O JSON parece completo? Sim, o Json veio completo contendo todas as informações da nave.

## Parte 2 — Extraindo campos específicos

Agora você vai executar os scripts e **completar as respostas**.

### 2.1 Extraindo campos do personagem

**Tarefa:** execute o bloco e depois responda.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome:", dados["name"])
print("Altura:", dados["height"])
print("Cor dos olhos:", dados["eye_color"])
print("Gênero:", dados["gender"])

"""**Perguntas**
1. Qual campo foi usado para mostrar o nome? **dados["name"]**
2. Qual campo foi usado para mostrar a altura? **dados["height"]**
3. Se você fosse QA, quais desses campos validaria primeiro? Eu validaria primeiro o **nome**, pois é o dado principal, através dele conseguiria dar sequência a outros campos.

### 2.2 Extraindo campos do planeta

**Tarefa:** execute o bloco e complete as respostas.
"""

url = "https://swapi.dev/api/planets/2/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome do planeta:", dados["name"])
print("Clima:", dados["climate"])
print("Terreno:", dados["terrain"])
print("População:", dados["population"])

"""**Perguntas**
1. O campo população parece numérico? sim, ele puxa o numero de população do planeta.
Sim. O valor retornado é 2000000000, que representa um número inteiro grande.
2. O clima foi retornado corretamente? sim, está sendo retornando corretamente.
Sim. O campo climate retornou temperate, que indica clima
3. Se você fosse QA, o que validaria nesse planeta?
Eu validaria:

Se o campo name existe

Se o campo population é numérico

Se os campos climate e terrain estão presentes

Se o status code é 200 temperado.

## Parte 3 — Pensando como QA

Agora você vai trabalhar com validações simples.

### 3.1 Validações básicas

**Tarefa:** execute o bloco abaixo e depois escreva o que cada validação verifica.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Validação 1 - status 200:", response.status_code == 200)
print("Validação 2 - campo 'name' existe:", "name" in dados)
print("Validação 3 - nome não está vazio:", dados["name"] != "")
print("Validação 4 - campo 'height' existe:", "height" in dados)

"""**Explique com suas palavras**
1. O que a validação 1 verifica? Verifica se a conexão da API está funcionando, a partir do status code 200.
2. O que a validação 2 verifica? Verifica se o campo de nome existe em dados (api).
3. O que a validação 3 verifica? Verifica se o nome não está vazio, diferente de "".
4. O que a validação 4 verifica? Verifica se o campo de altura existe em dados (api).

### 3.2 Complete as validações

**Tarefa:** execute o bloco abaixo. Ele já está funcionando. Depois, alterem as expressões se o professor pedir outra nave ou outro endpoint. Em seguida, expliquem por que cada validação faz sentido para QA.
"""

url = "https://swapi.dev/api/starships/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Status 200:", response.status_code == 200)

# Os exemplos abaixo já estão corretos e executáveis.
# Se o professor pedir, vocês podem alterar para validar outros campos.
print("Campo 'name' existe:", "name" in dados)
print("Campo 'model' existe:", "model" in dados)
print("Nome não está vazio:", dados["name"] != "")

"""Sim, faz sentindo essas validações pois facilita a realização de testes da nave espacial.

1° verifica se o nome existe, está em dados

2° verifica a exisitencia do modelo da nave

3° Verifica se o nome da nave não está vazio

OBS: os resultados são no formato **booleano**

## Parte 4 — Testes automatizados com assert

Agora vocês vão trabalhar sobre scripts já prontos. Os asserts abaixo já executam sem erro. A tarefa do grupo é **entender o que cada linha valida**, ajustar se o professor pedir outro recurso e registrar as respostas.

### 4.1 Assert no personagem

**Tarefa:** execute o bloco. Depois, expliquem o que cada assert valida e, se quiserem, alterem o endpoint para outro personagem.
"""

url = "https://swapi.dev/api/people/50/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "name" in dados, "Erro: campo name não encontrado"
assert dados["name"] != "", "Erro: nome vazio"

print("Todos os testes do personagem passaram!")

"""Endpoint testado: https://swapi.dev/api/people/13/


*   assert response.status_code == 200, "Erro: status inesperado"

    *   Valida se a requisição retornou o status HTTP 200 (OK).


*   assert "name" in dados, "Erro: campo name não encontrado"

     *    Verifica se o campo "name" existe no JSON retornado.


*   assert dados["name"] != "", "Erro: nome vazio"

    *   Garante que o campo "name" não está vazio.

### 4.2 Assert na nave

**Tarefa:** execute o bloco. Depois, descrevam qual campo foi validado em cada assert e proponham mais 1 validação extra em Markdown.
"""

url = "https://swapi.dev/api/starships/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado"
assert "manufacturer" in dados, "Erro: fabricante não encontrado"
assert dados["model"] != "", "Erro: modelo vazio"

print("Todos os testes da nave passaram!")

"""Endpoint testado: https://swapi.dev/api/starships/10/


*   assert response.status_code == 200, "Erro: status inesperado"

    * Valida se a requisição retornou o status HTTP 200 (OK).


*   assert "manufacturer" in dados, "Erro: fabricante não encontrado"

    * Verifica se o campo "manufacturer" existe no JSON.


*   assert dados["model"] != "", "Erro: modelo vazio"

    *   Garante que o campo "model" não está vazio.

## Parte 5 — Cenário negativo

Agora você vai observar como a API se comporta quando pedimos um recurso inexistente.
"""

url = "https://swapi.dev/api/people/9999/"
response, origem = buscar_endpoint(url)

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print("Texto retornado:")
print(response.text)

"""**Perguntas**
1. Qual status code foi retornado? code 404.

2. Esse comportamento está correto? sim o comportamentou está correto.

3. Por que um QA deve testar cenários negativos? deve testar cenários negativos para verificar como o sistema se comporta diante de erros, entradas invalidas ou situação inesperada.

## Parte 6 — Mini desafio final

Agora você vai alterar apenas o endpoint da função abaixo e gerar um pequeno resumo.
"""

def resumo_recurso(url):
    response, origem = buscar_endpoint(url)
    print("Origem dos dados:", origem)
    print("Status Code:", response.status_code)

    if response.status_code != 200:
        print("Recurso não encontrado.")
        return

    dados = response.json()

    for chave, valor in dados.items():
        print(f"{chave}: {valor}")

# ALTERE O ENDPOINT ABAIXO PARA TESTAR OUTRO RECURSO
resumo_recurso("https://swapi.dev/api/planets/1/")

"""**Respostas finais**
Qual endpoint você testou no desafio? 30

Qual foi o status code? 200

Qual campo chamou mais a sua atenção? O campo de films, pois referencia filmes que o personagem aparece.

Se você fosse QA, quais 3 validações faria nesse recurso?

1.   Verificar se o status code é 200.
2.   Validar se o campo "name" existe e não está vazio
3.   Checar se o campo "height" é numérico.

# Entrega da atividade

Entreguem:

1. O notebook preenchido  
2. As respostas em Markdown  
3. Os scripts ajustados  
4. Os asserts analisados e/ou adaptados  
5. Uma conclusão curta do grupo: **quais foram as 3 validações mais importantes?**

## Fechamento
Ao final desta atividade, vocês praticaram:

- leitura de resposta JSON
- análise de status code
- validação de campos
- pensamento de QA
- testes simples com assert
- análise de cenário negativo
"""