# -*- coding: utf-8 -*-
"""Copy of Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUUU3S2D_wFv-ywThKOUSE2p4vT_bS1y

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**  Conta "pepper" criada no sistema.
**Pré-condição:**  Rodar banco
**Passos:**  
1.  banco.depositar('pepper', 0)
2.  OK - Depósito realizado: 0
3.  OK - Depósito realizado: 0
**Resultado esperado:** O sistema deve impedir depósitos com valor igual a zero e apresentar uma mensagem informando que o valor precisa ser maior que 0.
**Resultado obtido:**  OK - Depósito realizado: 0
**Status (Pass/Fail):**  Fail
**Evidência:**  Teste N1 – Tentativa de depósito com valor zero. O sistema permitiu a operação e exibiu “OK - Depósito realizado: 0”.

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:**  
**Pré-condição:**  
**Passos:**  
1.  banco.sacar('pepper',8000)
2.  Aguardar a resposta do sistema
3.  Analisar o resultado obtido e tentar resolver
**Resultado esperado:**  O sistema deve bloquear a operação de saque quando o valor solicitado for maior que o saldo disponível e exibir mensagem de saldo insuficiente.
**Resultado obtido:**  ERRO - Saldo insuficiente
**Status (Pass/Fail):**  Pass
**Evidência:**  Teste N3 – Tentativa de saque acima do saldo disponível. O sistema retornou “ERRO - Saldo insuficiente”.

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  
**Pré-condição:**  
**Passos:**  
1.  banco.transferir('pepper', 'rodrigo', 900)
2.  Ver a resposta do sistema
3.  Analiser resultado obtido
**Resultado esperado:**  O sistema não deve permitir a transferência para uma conta que não esteja cadastrada e deve informar que a conta de destino não foi encontrada.
**Resultado obtido:** ERRO - Conta destino não encontrada
**Status (Pass/Fail):**  Pass
**Evidência:**  Teste N4 – Transferência realizada para uma conta inexistente. O sistema apresentou a mensagem “ERRO - Conta destino não encontrada”.

# PARTE 05 — Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  Sistema aceita depósito com valor igual a zero
**Severidade (Baixa/Média/Alta):**  Baixa
**Prioridade (Baixa/Média/Alta):**  Baixa
**Ambiente:** Google Colab / Python 3.x / Banco do Stark: Colab

**Descrição:** Foi identificado que o sistema permite a realização de depósitos com valor igual a zero. Esse comportamento não está de acordo com a regra de negócio do sistema bancário, que exige que depósitos tenham valor maior que zero.

**Passos para reproduzir:**  
1.  Executar o comando abaixo no sistema: banco.depositar('tony', 0)
2.  Observar a mensagem retornada pelo sistema.
3.  Conferir o saldo ou extrato da conta para confirmar o registro da operação.

**Resultado esperado:** O sistema deveria impedir o depósito e informar que o valor precisa ser maior que zero.  
**Resultado obtido:**  OK - Depósito realizado: 0
**Evidência:**  Teste N1 – Depósito com valor zero
OK - Depósito realizado: 0
**Impacto/Risco:**  Permite operações inválidas dentro do sistema, podendo causar inconsistências nas regras financeiras.

## Template — Bug Report
**Título:**  Sistema permite depósito com valor negativo
**Severidade (Baixa/Média/Alta):**  Média
**Prioridade (Baixa/Média/Alta):**  Média
**Ambiente:** Google Colab

**Descrição:**  O sistema não valida corretamente o valor informado no depósito e aceita valores negativos, o que não deveria ser permitido.

**Passos para reproduzir:**  
1.  Executar o comando: banco.depositar('tony', -50)
2.  Observar a mensagem retornada pelo sistema.
3.  Verificar o saldo ou extrato da conta para confirmar o registro da operação.

**Resultado esperado:**  O sistema deveria bloquear a operação e informar que o valor do depósito é inválido.
**Resultado obtido:**  OK - Depósito realizado: -50
**Evidência:**  Teste – Depósito com valor negativo
OK - Depósito realizado: -50
**Impacto/Risco:**  Pode afetar o saldo da conta de forma incorreta e comprometer a lógica das operações bancárias.

## Template — Bug Report
**Título:**  Extrato apresenta registros duplicados de transações
**Severidade (Baixa/Média/Alta):**  Baixa
**Prioridade (Baixa/Média/Alta):**  Média
**Ambiente:** Google Colab

**Descrição:**  O extrato da conta apresenta registros repetidos de algumas operações, indicando possível duplicação no armazenamento das transações

**Passos para reproduzir:**  
1.  Executar o cenário inicial do notebook.
2.  Realizar algumas operações, por exemplo: banco.depositar('tony', 100) /banco.sacar('tony', 50)
3.  Consultar o extrato da conta para verificar os registros:
banco.mostrar_extrato('tony')

**Resultado esperado:**  Cada transação deveria aparecer apenas uma vez no extrato.
**Resultado obtido:**  O extrato apresenta operações duplicadas.
**Evidência:**  Exemplo de saída:
('deposito', 100)
('deposito', 100)
('saque', 50)
('saque', 50)

**Impacto/Risco:**  Pode causar confusão ao usuário e prejudicar a confiabilidade do histórico financeiro da conta.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""