# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).


## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.


In [3]:
# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')


Banco do Stark carregado!


Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**


In [4]:
# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')


=== CRIAR CONTAS ===
OK - Conta criada para: tony
OK - Conta criada para: pepper
OK - Conta criada para: banner

=== DEPÓSITOS ===
OK - Depósito realizado: 1000
OK - Depósito realizado: 500

=== SALDOS ===
SALDO tony = 1000.0
SALDO pepper = 500.0

=== SAQUE ===
OK - Saque realizado: 200
SALDO tony = 800.0

=== TRANSFERÊNCIA ===
OK - Transferência realizada: 100
SALDO tony = 700.0
SALDO pepper = 600.0

=== EXTRATO (tony) ===
EXTRATO: tony
 - ('deposito', 1000)
 - ('saque', 200)
 - ('transferencia_saida', 100)

TESTES NEGATIVOS (QA)

Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0

Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 600.0

Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente

Teste N4 - Transferência para conta inexistente
ERRO - Conta destino não encontrada

Teste N5 - Consulta de conta inexistente (saldo)
ERRO - Conta não encontrada: natasha

Teste N6 - Consulta de conta inexistente (extrato)
ERRO -

# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente


## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:** Validar que depósito com valor zero é rejeitado pelo sistema  
**Pré-condição:** Banco carregado; conta 'tony' criada com saldo R$ 700,00  
**Passos:**  
1. Carregar o banco e criar conta 'tony'
2. Realizar depósito inicial de R$ 1000
3. Executar banco.depositar('tony', 0)

**Resultado esperado:** ERRO - Valor de depósito inválido: deve ser maior que zero  
**Resultado obtido:** OK - Depósito realizado: 0  
**Status (Pass/Fail):** Fail  
**Evidência:**  
```
Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0
```

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:** Validar que depósito com valor negativo é rejeitado e não altera o saldo  
**Pré-condição:** Banco carregado; conta 'tony' com saldo R$ 700,00  
**Passos:**  
1. Carregar o banco e criar conta 'tony'
2. Depositar R$ 1000 para estabelecer saldo inicial
3. Executar banco.depositar('tony', -100)

**Resultado esperado:** ERRO - Valor de depósito inválido: deve ser maior que zero; saldo permanece inalterado  
**Resultado obtido:** OK - Depósito realizado: -100; saldo caiu de 700.0 para 600.0  
**Status (Pass/Fail):** Fail  
**Evidência:**  
```
Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 600.0
```

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:** Validar que saque com valor acima do saldo disponível é bloqueado  
**Pré-condição:** Banco carregado; conta 'tony' com saldo R$ 600,00  
**Passos:**  
1. Carregar o banco e criar conta 'tony'
2. Depositar R$ 1000 e realizar operações até saldo = 600.0
3. Executar banco.sacar('tony', 100000)

**Resultado esperado:** ERRO - Saldo insuficiente  
**Resultado obtido:** ERRO - Saldo insuficiente  
**Status (Pass/Fail):** Pass  
**Evidência:**  
```
Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente
```

# PARTE 05 — Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo


## Template — Bug Report
**Título:** Sistema aceita depósito com valor zero  
**Severidade (Baixa/Média/Alta):** Média  
**Prioridade (Baixa/Média/Alta):** Média  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O método depositar() não valida se o valor é maior que zero. Ao receber 0, o sistema confirma o depósito normalmente, violando a regra de negócio (Requisito 2).  

**Passos para reproduzir:**  
1. Carregar banco: banco = BancoDoStark()
2. Criar conta: banco.criar_conta('tony')
3. Executar: banco.depositar('tony', 0)

**Resultado esperado:** ERRO - Valor de depósito inválido: deve ser maior que zero  
**Resultado obtido:** OK - Depósito realizado: 0  
**Evidência:**  
```
Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0
```
**Impacto/Risco:** Extrato poluído com transações sem valor; impacto em relatórios financeiros e auditoria.

## Template — Bug Report
**Título:** Sistema aceita depósito negativo e reduz saldo indevidamente  
**Severidade (Baixa/Média/Alta):** Alta  
**Prioridade (Baixa/Média/Alta):** Alta  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O método depositar() não rejeita valores negativos. Um depósito de -100 é processado com sucesso, diminuindo o saldo — comportamento equivalente a um saque não autorizado, sem passar pela validação do método sacar().  

**Passos para reproduzir:**  
1. Carregar banco e criar conta: banco.criar_conta('tony')
2. Depositar valor inicial: banco.depositar('tony', 1000)
3. Executar: banco.depositar('tony', -100) e verificar com banco.saldo_atual('tony')

**Resultado esperado:** ERRO - Valor de depósito inválido: deve ser maior que zero; saldo não se altera  
**Resultado obtido:** OK - Depósito realizado: -100; saldo diminuiu de 700.0 para 600.0  
**Evidência:**  
```
Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 600.0
```
**Impacto/Risco:** Crítico financeiro — permite reduzir saldo sem validação de segurança. Possível vetor de exploração intencional.

## Template — Bug Report
**Título:** Transferência não impede que origem e destino sejam a mesma conta  
**Severidade (Baixa/Média/Alta):** Alta  
**Prioridade (Baixa/Média/Alta):** Alta  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O método transferir() não verifica se origem == destino. Transferir para a própria conta não altera o saldo, mas gera duas entradas incorretas no extrato (transferencia_saida e transferencia_entrada), violando a integridade do histórico (Requisito 4 e 6).  

**Passos para reproduzir:**  
1. Carregar banco e criar conta: banco.criar_conta('tony')
2. Depositar R$ 500: banco.depositar('tony', 500)
3. Executar: banco.transferir('tony', 'tony', 100) e verificar extrato

**Resultado esperado:** ERRO - Transferência para a mesma conta não é permitida  
**Resultado obtido:** OK - Transferência realizada: 100 + 2 registros no extrato sem movimentação real  
**Evidência:** Identificado por análise do código — ausência de validação if origem == destino no método transferir().  
**Impacto/Risco:** Extrato adulterado; potencial uso para manipular histórico de transações ou burlar auditorias internas.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.

In [ ]:
# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')


Pronto! Execute seus testes aqui.


## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.
