# -*- coding: utf-8 -*-
"""Atividade_QA_Giovani_Ribeiro_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZRIA53zmgzFbc88IDRV6nZFtuRJdhxL

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo: Depósito negativo**  
**Pré-condição: Conta “tony” com saldo 700.0**  
**Passos:**  
1. Executar banco.depositar('tony', -100)

**Resultado esperado: Depósito inválido, saldo não deve mudar**  
**Resultado obtido: Depósito realizado, saldo atualizado para 600.0**  
**Status (Pass/Fail): Fail**  
**Evidência:**  
Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 600.0

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo: Saque acima do saldo**  
**Pré-condição: Conta “tony” com saldo 600.0**  
**Passos:**  
1.  Executar banco.sacar('tony', 100000)

**Resultado esperado: Saque inválido, mensagem de saldo insuficiente, saldo permanece 600.0**  
**Resultado obtido: Mensagem de erro: ERRO - Saldo insuficiente**  
**Status (Pass/Fail): Pass**  
**Evidência:**  
Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo: Depósito com valor zero**  
**Pré-condição: Conta “tony” criada com saldo 700.0**  
**Passos:**  
1.  Executar banco.depositar('tony', 0)

**Resultado esperado: Depósito inválido, saldo não deve mudar**  
**Resultado obtido: Depósito realizado, saldo atualizado para 700.0**  
**Status (Pass/Fail): Fail**  
**Evidência:**  
Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0

Saldo após depósitos inválidos
SALDO tony = 600.0

# PARTE 05 — Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título: Sistema aceita depósito com valor zero ou negativo**  
**Severidade (Baixa/Média/Alta): Alta**  
**Prioridade (Baixa/Média/Alta): Alta**  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição: O sistema permite depósitos com valor zero ou negativo, alterando o saldo da conta, o que viola a regra de negócio.**  

**Passos para reproduzir:**  
1.  Criar uma conta: banco.criar_conta('tony')
2.  Depositar zero: banco.depositar('tony', 0)
3.  Depositar negativo: banco.depositar('tony', -100)
  Consultar saldo: banco.saldo_atual('tony')

**Resultado esperado: Depósitos com valor ≤ 0 devem ser rejeitados, saldo não deve ser alterado.**  
**Resultado obtido: Depósitos realizados, saldo alterado para 600.0**  
**Evidência:**  

Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0

Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 600.0

**Impacto/Risco: Permite que o saldo da conta seja manipulado indevidamente, causando inconsistências financeiras.**

## Template — Bug Report
**Título: Sistema permite transferência sem validação completa do destinatário antes da operação**  
**Severidade (Baixa/Média/Alta): Média**  
**Prioridade (Baixa/Média/Alta): Média**  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição: Ao tentar realizar uma transferência para uma conta que não existe, o sistema retorna uma mensagem de erro. Porém, não há validação prévia clara da existência da conta antes da tentativa da operação, o que indica falha na lógica de validação do fluxo da transferência.**  

**Passos para reproduzir:**  
1.  Criar conta tony
2.  Executar a transferência para uma conta inexistente: banco.transferir('tony', 'thor', 50)

**Resultado esperado: O sistema deveria validar previamente se a conta de destino existe antes de iniciar a operação de transferência.**  
**Resultado obtido: O sistema retorna erro após tentativa de transferência.**  
**Evidência:**  

Teste N4 - Transferência para conta inexistente
ERRO - Conta destino não encontrada

**Impacto/Risco: Pode indicar falha na validação do fluxo da operação, aumentando o risco de erros em transações ou inconsistência no sistema.**

## Template — Bug Report
**Título: Sistema permite consulta de saldo e extrato para contas inexistentes antes de validação adequada**  
**Severidade (Baixa/Média/Alta): Baixa**  
**Prioridade (Baixa/Média/Alta): Média**  
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição: Ao consultar saldo ou extrato de uma conta inexistente, o sistema retorna uma mensagem de erro. No entanto, a aplicação permite que a chamada da função seja realizada sem verificação prévia da existência da conta.**  

**Passos para reproduzir:**  
1.  Executar consulta de saldo: banco.saldo_atual('natasha')
2.  Executar consulta de extrato: banco.mostrar_extrato('natasha')


**Resultado esperado: O sistema deveria validar previamente se a conta existe antes de tentar acessar os dados da conta.**  
**Resultado obtido:**  

Teste N5 - Consulta de conta inexistente (saldo)
ERRO - Conta não encontrada: natasha

Teste N6 - Consulta de conta inexistente (extrato)
ERRO - Conta não encontrada: natasha

**Evidência: Saída exibida diretamente no notebook durante a execução dos testes negativos.**  
**Impacto/Risco: Pode gerar falhas na experiência do usuário e indica ausência de validação preventiva na lógica de acesso às contas.**

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

print("====================================")
print("TESTES QA - BANCO DO STARK")
print("====================================")


banco.criar_conta('tony')
banco.criar_conta('pepper')

banco.depositar('tony', 500)

print("\nTESTE 1 - Depósito com valor 0")
print("esperado: sistema rejeitar")
print("obtido:")
banco.depositar('tony', 0)
banco.saldo_atual('tony')

print("\nTESTE 2 - Depósito negativo")
print("esperado: sistema rejeitar")
print("obtido:")
banco.depositar('tony', -100)
banco.saldo_atual('tony')

print("\nTESTE 3 - Saque acima do saldo")
print("esperado: erro saldo insuficiente")
print("obtido:")
banco.sacar('tony', 100000)
banco.saldo_atual('tony')

print("\nTESTE 4 - Transferência para conta inexistente")
print("esperado: erro conta destino")
print("obtido:")
banco.transferir('tony', 'thor', 50)

print("\nTESTE 5 - Consulta saldo conta inexistente")
print("esperado: erro conta não encontrada")
print("obtido:")
banco.saldo_atual('natasha')

print("\nTESTE 6 - Consulta extrato conta inexistente")
print("esperado: erro conta não encontrada")
print("obtido:")
banco.mostrar_extrato('natasha')

print("FIM DOS TESTES QA")

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""