# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).


## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.


In [ ]:
# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')


Banco do Stark carregado!


Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**


In [ ]:
# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')


=== CRIAR CONTAS ===
OK - Conta criada para: tony
OK - Conta criada para: pepper
OK - Conta criada para: banner

=== DEPÓSITOS ===
OK - Depósito realizado: 1000
OK - Depósito realizado: 500

=== SALDOS ===
SALDO tony = 1000.0
SALDO pepper = 500.0

=== SAQUE ===
OK - Saque realizado: 200
SALDO tony = 800.0

=== TRANSFERÊNCIA ===
OK - Transferência realizada: 100
SALDO tony = 700.0
SALDO pepper = 600.0

=== EXTRATO (tony) ===
EXTRATO: tony
 - ('deposito', 1000)
 - ('saque', 200)
 - ('transferencia_saida', 100)

TESTES NEGATIVOS (QA)

Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0

Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 600.0

Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente

Teste N4 - Transferência para conta inexistente
ERRO - Conta destino não encontrada

Teste N5 - Consulta de conta inexistente (saldo)
ERRO - Conta não encontrada: natasha

Teste N6 - Consulta de conta inexistente (extrato)
ERRO -

# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente


## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:** CRIAR CONTAS
**Pré-condição:**  RODAR O BANCO
**Passos:**  
1. RODAR O BANCO
2. BANCO.CRIAR_CONTA('TONY')
3.  
**Resultado esperado:**  OK - CONTA CRIADA PARA : TONY
**Resultado obtido:**    OK - CONTA CRIADA PARA : TONY
**Status (Pass/Fail):**  PASS
**Evidência:**  
=== CRIAR CONTA ===


## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:**  Validar depósito com valor negativo.
**Pré-condição:**  Conta "tony" previamente criada.
**Passos:**  
1.  banco.depositar('tony', -100)
2.  Verificar a mensagem de saída.
3.  Verificar o saldo da conta.
**Resultado esperado:**  O sistema deve impedir o depósito e exibir mensagem de erro (valor deve ser > 0). O saldo não deve ser alterado
**Resultado obtido:** OK - Depósito realizado: -100. O saldo foi reduzido (subtraído).
**Status (Pass/Fail):**  FAIL
**Evidência:**  Teste N2 - Depósito negativo -> OK - Depósito realizado: -100 | SALDO tony = 600.0


## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  Validar saque acima do saldo disponível.
**Pré-condição:**  Conta "tony" com saldo de 800.0.
**Passos:**  
1.  Chamar a função banco.sacar('tony', 100000).
2.  
3.  
**Resultado esperado:** O sistema deve exibir "ERRO - Saldo insuficiente" e não realizar a operação.
**Resultado obtido:** ERRO - Saldo insuficiente.
**Status (Pass/Fail):**  PASS
**Evidência:**  Teste N3 - Saque acima do saldo -> ERRO - Saldo insuficiente


# PARTE 05 — Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo


## Template — Bug Report
**Título:**  Sistema permite depósito de valores negativos subtraindo o saldo.
**Severidade (Baixa/Média/Alta):**  ALTA
**Prioridade (Baixa/Média/Alta):**  ALTA
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** Ao realizar um depósito com valor negativo, o sistema aceita a operação e acaba subtraindo o valor do saldo do cliente, tratando o "depósito" como um saque indevido.

**Passos para reproduzir:**  
1.  Criar conta para 'tony'.
2.  Realizar depósito válido de 1000.
3.  Realizar depósito de -100 via banco.depositar('tony', -100).

**Resultado esperado:**  Erro informando que o depósito deve ser maior que zero.
**Resultado obtido:** O sistema exibe "OK" e o saldo cai para 900.
**Evidência:**  SALDO tony = 600.0 (após os testes negativos no console).
**Impacto/Risco:**  
LENTIDÃO NO SISTEMA PARA LEITURA SEM VALORESPerda de dinheiro para o cliente e quebra da regra de negócio "Saldo nunca pode ficar negativo"

## Template — Bug Report
**Título:** Sistema aceita depósitos de valor zero (R$ 0,00).
**Severidade (Baixa/Média/Alta):**  BAIXA
**Prioridade (Baixa/Média/Alta):**  MÉDIA
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O sistema permite a execução da função de depósito mesmo quando o valor informado é zero, gerando registros inúteis no extrato.

**Passos para reproduzir:**  
1.  Executar banco.depositar('tony', 0).
2.  
3.  

**Resultado esperado:**  O sistema deve validar que o valor é maior que zero e impedir a operação.
**Resultado obtido:** OK - Depósito realizado: 0.
**Evidência:**  Teste N1 - Depósito com valor zero -> OK - Depósito realizado: 0.
**Impacto/Risco:**  Poluição do extrato do cliente e processamento desnecessário de transações sem valor monetário.

## Template — Bug Report
**Título:** Falta de validação para titular com nome vazio ou espaços.
**Severidade (Baixa/Média/Alta):**  MÉDIA
**Prioridade (Baixa/Média/Alta):**  BAIXA
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  O sistema permite criar contas onde o nome do titular é uma string vazia ("") ou apenas espaços ("   ").

**Passos para reproduzir:**  
1.  Executar banco.criar_conta(" ").
2.  
3.  

**Resultado esperado:**  Erro informando que o nome do titular não pode ser vazio.
**Resultado obtido:** O sistema cria a conta normalmente.
**Evidência:**  Pode ser gerada rodando banco.criar_conta("") na última célula
**Impacto/Risco:**  Dificuldade de identificação de clientes e inconsistência no banco de dados.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.

In [ ]:
# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')


Pronto! Execute seus testes aqui.


In [1]:
# Teste de transferência para si mesmo (Regra: não pode transferir para si mesmo)
print('Teste Bug - Transferir para si mesmo')
banco.transferir('tony', 'tony', 50)
banco.saldo_atual('tony')

# Teste de nome vazio
print('\nTeste Bug - Nome vazio')
banco.criar_conta('   ')

Teste Bug - Transferir para si mesmo


NameError: name 'banco' is not defined

## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.
