# -*- coding: utf-8 -*-
"""Atividade_QA_Matheus_Bondezan_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXvwAOxYg92NraF4evbY9qg6PIyuEJYp

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**  Validar que o sistema não deve aceitar depósito com valor zero
**Pré-condição:**  rodar banco stark
**Passos:**  
1.  RODAR O BANCO
2.  Realizar depósito com valor 0 na conta "tony".

**Resultado esperado:**  O sistema deve rejeitar o depósito e exibir erro informando que o valor deve ser maior que 0.
**Resultado obtido:** O sistema aceitou o depósito de valor 0.
**Status (Pass/Fail):**  fail
**Evidência:**  
Depósito com valor zero OK - Depósito realizado: 0

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:**   Validar depósito com valor negativo
**Pré-condição:**  Conta "---" criada e existente no sistema
**Passos:**  
1.  rodar o banco
2.  Executar banco.depositar("---", -100)
3.  Consultar saldo com banco.saldo_atual("---")
**Resultado esperado:**   o sistema deve impedir depósitos negativos e retornar uma mensagem de erro
**Resultado obtido:**  o sistema aceita o depósito negativo e reduz o saldo da conta
**Status (Pass/Fail):**  fail
**Evidência:** OK - Depósito realizado: -100 SALDO vitinho = -100.0
"""



"""## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  validar saque acima do saldo dispónivel
**Pré-condição:**  conta criada e com saldo disponível
**Passos:**  
1.  rodar o banco
2.  Depositar 1000 na conta
3.  Executar banco.sacar("---", 100000)
**Resultado esperado:**  o sistema deve bloquear o saque e mostrar mensagem de erro informando saldo insuficiente
**Resultado obtido:**  o sistema bloqueia o saque e exibe a mensagem de erro corretamente
**Status (Pass/Fail):**  pass
**Evidência:**  Depósito realizado: 1000 ERRO - Saldo insuficiente

# PARTE 05 — Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  deposito com valor zero
**Severidade (Baixa/Média/Alta):**  baixa
**Prioridade (Baixa/Média/Alta):**  baixa
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
sistema aceita depósitos com valor igual a zero, o que viola a regra de negócio que exige que o valor do depósito seja maior que zero

**Passos para reproduzir:**  
1.  rodar o banco
2.  Executar banco.depositar("---", o)
3.  

**Resultado esperado:**  sistema deveria rejeitar a operação e exibir mensagem de erro informando que o valor do depósito deve ser maior que zero
**Resultado obtido:**  o sistema aceita o depósito e registra a operação
**Evidência:**   Depósito realizado: 0
**Impacto/Risco:**  
lentidão no sistema para leitura

## Template — Bug Report
**Título:**  Sistema permite depósito com valor negativo
**Severidade (Baixa/Média/Alta):**  Alta
**Prioridade (Baixa/Média/Alta):**  Alta
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  o sistema permite realizar depósitos com valores negativos, o que pode reduzir o saldo da conta e causar inconsistência nas regras bancárias

**Passos para reproduzir:**  
1.  rodar banco
2.  Executar banco.depositar("---", -100)
3.  

**Resultado esperado:**  o sistema deveria bloquear depósitos negativos e exibir mensagem de erro
**Resultado obtido:**  sistema aceita o valor negativo e altera o saldo
**Evidência:**  Depósito realizado: -100
**Impacto/Risco:**  pode gerar manipulação indevida de saldo e inconsistência no controle financeiro

## Template — Bug Report
**Título:**  Sistema permite criação de conta com titular vazio ou apenas espaços
**Severidade (Baixa/Média/Alta):**  Média
**Prioridade (Baixa/Média/Alta):**  Média
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  
O sistema não valida se o campo de titular da conta está vazio ou contém apenas espaços. Segundo os requisitos do sistema, o titular não pode ser vazio nem conter apenas espaços. Atualmente a aplicação cria a conta normalmente.
**Passos para reproduzir:**  
1.  Executar o comando para criar uma conta.
2.  Informar o titular como " " (apenas espaço) ou "" (vazio).
3.  

**Resultado esperado:**  O sistema deve impedir a criação da conta e exibir mensagem de erro informando que o titular é inválido.
**Resultado obtido:**  sistema cria a conta normalmente sem validar o nome do titular.
**Evidência:**  O método criar_conta() apenas verifica se o titular já existe, não validando se o valor é vazio:
def criar_conta(self, titular: str): if titular in self.contas: print('ERRO - Conta já existe:', titular) return self.contas[titular] = Conta(titular)
**Impacto/Risco:**  Pode permitir a criação de contas inválidas ou difíceis de identificar no sistema, causando inconsistência nos dados e dificultando o gerenciamento das contas.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""